### ISSUE TITLE
Update solc dependency to 0.5

### ISSUE THREAD

**Issue by nitper** [austintgriffith/clevis#28]
Can we update the `solc` dependency to `0.5`?

**Comment by austintgriffith** [comment]
try: "npm install --save solc@0.5.2"

We'll get that in the latest version and push it ourselves soon!

**Comment by Dziubutkus** [comment]
@austintgriffith It still compiles with "0.4.25+commit.59dbf8f1.Emscripten.clang", I cant make it compile with 0.5.*
Deleted node_modules, changed package.json, clevis still used 0.4.25 compiler.

**Comment by nitper** [comment]
I started working on a fix - I should have a PR tomorrow.

**Comment by nitper** [comment]
@Dziubutkus you can try testing my PR #30
