### ISSUE TITLE
With the new install dirs, you can't bring in an existing project any more

### ISSUE THREAD

**Issue by austintgriffith** [austintgriffith/clevis#9]
You need to be able to clone down an existing clevis project and run 

```
clevis init
npm i
clevis test full
npm start
```

and everything should work

It is failing to install both mocha and react scripts:

![image](https://user-images.githubusercontent.com/2653167/47218482-1d377280-d369-11e8-98cf-5890dc3c91e3.png)

![image](https://user-images.githubusercontent.com/2653167/47218489-21fc2680-d369-11e8-8263-12094aefbe72.png)

**Comment by rrecuero** [comment]
Removing package-lock.json before running npm install fixes it. 

Were you using the linked clevis in the computer that pushed package-lock.json?

**Comment by austintgriffith** [comment]
damn, getting babel issues now. Going to give up tonight and try tomorrow. 

So you can clone down https://github.com/austintgriffith/social-login.git, delete the package-lock.json, clevis init, npm i, and npm start works for you? 

Maybe I have something wrong on my end. Will attack it in the morning.

![image](https://user-images.githubusercontent.com/2653167/47250179-9a4f0000-d3da-11e8-81aa-9dfb7a3b4048.png)

**Comment by austintgriffith** [comment]
Okay I think I found the problem. 

Dapparatus is packaged up with a version of babel that CRA warns about, but it isn't necessarily a problem. 

You can just add "SKIP_PREFLIGHT_CHECK=true" to a ".env" file and it runs fine. I will add this right into the clevis init so this is avoided in the future.

**Comment by rrecuero** [comment]
Thanks! I'll add this
